# Site settings
title: Frank Blog
SEOTitle: Frank Blog
header-img: img/home-bg.jpg
email: shufanhao@126.com
description: "Software Engineer | Java, Golang, Kubernetes, Docker, 与你一起发现更大的世界。"
keyword: "shufanhao, 范浩, 范浩的博客, Frank Blog, 博客, 个人网站, 互联网, Web, Java, Kubernetes"
url: "https://shufanhao.github.io"              # your host, for absolute URL
baseurl: ""                                     # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
weibo_username: Frank范-sunny
zhihu_username: shufanhao
github_username: shufanhao
# twitter_username:   shufanhao
#facebook_username:  shufanhao
#linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
disqus_username: disqus_Zfj1CZNyWq

# Netease settings
netease_comment: false



# Analytics settings
# Baidu Analytics 
ba_track_id: 5ae26ff22d9f0acf7104803a3779dfa3

# Google Analytics
ga_track_id: 'G-QH4G00DRMM'
ga_domain: auto



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Frank Fan 喜欢用程序让生活更美好 <br> like make life better by program."
sidebar-avatar: https://github.com/shufanhao.png # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false



# Friends
friends: [
    {
    #     title: "Su",
    #     href: "http://su.gallery/"
    #
    }
]
